[project]
name = "repeater_mapper"
version = "0.1.0"
requires-python = ">=3.12"
description = "A tool to parse, ingest and work ham radio repeater information."

dependencies = [
    "beautifulsoup4 ~= 4.14.0",
    "requests ~= 2.32.5",
    "geopy ~= 2.4.1",
]

[project.scripts]
repeater-mapper = "repeater_mapper.main:main"
